version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang
    container_name: app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app

  #MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "33067:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: golang
      MYSQL_PASSWORD: "golang"
      MYSQL_DATABASE: golang
    networks:
      default:
        aliases:
          - db
#Volumes
volumes:
  mysql: